title: My Portfolio
description: A portfolio showcasing Cybersecurity, Cloud Security, and DevSecOps projects.
theme: jekyll-theme-minimal
domain: averagejoesec.github.io
url: https://averagejoesec.github.io
baseurl: /averagejoesec.github.io/
