title: My Portfolio
description: A portfolio showcasing Cybersecurity, Cloud Security, and DevSecOps projects.
theme: jekyll-theme-minimal
url: "https://averagejoesec.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
